### ISSUE TITLE
Library not loaded: 

### ISSUE THREAD

**Issue by wenliabc2007** [tobefuturer/app2dylib#1]
dyld: Library not loaded: /usr/lib/abc.dylib
  Referenced from: /var/containers/Bundle/Application/8BBEFF4A-6511-46C5-B9EE-18A2E0249A9E/test.app/test
  Reason: image not found
这是什么原因？dylib有问题？

**Comment by tobefuturer** [comment]
谢谢来信，我的操作截图里好像少了一步，xcode 的 build phases 那里 有一个link binary with library
的选项，拖进工程的dylib好像被默认加上了， 你去掉试试看？

2016-10-13 13:44 GMT+08:00 wenliabc2007 notifications@github.com:

**Comment by wenliabc2007** [comment]
感谢大神～！可以用了。是不是 link binary with library 选项 是apple做了限制的。必须是系统的dylib才可以加载....而且是app启动的时候就全部加载到内存。那是不是说这样在需要时加载的方式甚至都可以骗过 apple的审核了／？

**Comment by tobefuturer** [comment]
还是要苹果审核的， dlopen的时候，也有一次签名验证的，不然会失败

**Comment by wenliabc2007** [comment]
配合JSPatch....简直是细思极恐～～iOS安全人员的又一项挑战...膝盖献上！！！
