### ISSUE TITLE
动态库内存释放，多次初始化问题

### ISSUE THREAD

**Issue by zyfu0000** [tobefuturer/app2dylib#2]
对逆向不甚了解，这个工程相见恨晚。
我们有尝试将多个项目的源码编译成动态库，通过dlopen加载，dlclose卸载。但是实际操作中内存不能完全释放，特别是诸多的单例和第三方库的内存占用。所以也没法多次初始化，只能保存每个应用保持一个实例常驻，内存压力很大。
求问有什么好的方式能用吗？我们试过重写malloc来保存分配的指针，卸载时统一delete，貌似不行。

**Comment by tobefuturer** [comment]
能给个实际数据吗  我看过支付宝的一些单例 应该不会特别大才对 

你说统一delete不行，原因是什么呢 ，直接delete内存地址应该是没有理由释放不掉吧，可能有部分malloc 你没统计到？

杨君

**Comment by zyfu0000** [comment]
我们项目有很多图像处理相关的，还有游戏，类似于把cocos2d打成动态库，游戏结束后能正常释放，也能正常重启游戏。实际delete释放途中会崩溃，也有可能是重复delete造成的，排查起来很费力，所以就放弃了。
