### ISSUE TITLE
dlopen failed

### ISSUE THREAD

**Issue by Sniper-yj** [tobefuturer/app2dylib#3]
dlopen failed ，error dlopen(/private/var/mobile/Containers/Bundle/Application/2B58BBB1-9348-46B0-90C4-3680B39A66A5/IphoneCom.app/libIphoneCom.dylib, 10): Library not loaded: @rpath/IphoneComFramework.framework/IphoneComFramework
  Referenced from: /private/var/mobile/Containers/Bundle/Application/2B58BBB1-9348-46B0-90C4-3680B39A66A5/IphoneCom.app/libIphoneCom.dylib
  Reason: image not found
按照你的步骤一步一步做，但是动态库还是load失败，不知道是什么原因，希望大神能够帮忙看下

**Comment by tobefuturer** [comment]
这个app本身就依赖于 他内部的动态库  你先找个支付宝练手看看？

2016-10-19 14:24 GMT+08:00 Sniper-yj notifications@github.com:

**Comment by Sniper-yj** [comment]
好的，我试一试

**Comment by Sniper-yj** [comment]
dlopen failed ，error dlopen(/private/var/mobile/Containers/Bundle/Application/3925AF3E-6C9F-43E2-8DF4-4BC607200EE2/IphoneCom.app/AlipayWallet2.dylib, 10): Symbol not found: _sqlite3_strglob
  Referenced from: /private/var/mobile/Containers/Bundle/Application/3925AF3E-6C9F-43E2-8DF4-4BC607200EE2/IphoneCom.app/AlipayWallet2.dylib
  Expected in: /usr/lib/libsqlite3.dylib
 in /private/var/mobile/Containers/Bundle/Application/3925AF3E-6C9F-43E2-8DF4-4BC607200EE2/IphoneCom.app/AlipayWallet2.dylib
我用支付宝试了下，报找不到_sqlite3_strglob这个符号，这是什么情况呀，和系统版本有关吗。。

**Comment by tobefuturer** [comment]
嗯 有可能，你换个设备，换个系统试试看？不一定要越狱机
