### ISSUE TITLE
请问， 拆分arm64架构和armv7s架构，进行转化后，如何让动态库支持arm64和armv7s ?

### ISSUE THREAD

**Issue by bbbang007** [tobefuturer/app2dylib#4]
app2dylib supports armv7 and arm64 archtecture, but not support fat file. Please use lipo to thin the image file first.

**Comment by tobefuturer** [comment]
命令行 libtool

**Comment by bbbang007** [comment]
感谢你的及时回复^ ^

**Comment by tobefuturer** [comment]
没事~

**Comment by bbbang007** [comment]
使用 gcc -dynamiclib -o  语句得到一个 Mach-O 64-bit dynamically linked shared library x86_64 动态库，无法使用，求助。。。

**Comment by tobefuturer** [comment]
命令行 man libtool 看文档

**Comment by cbangchen** [comment]
我是直接用两个分别打包出来的动态库再进行合并，这种做法是正确的吗

**Comment by bbbang007** [comment]
可以使用 lipo -create A.dylib B.dylib -o C.dylib
