### ISSUE TITLE
dlopen failed 

### ISSUE THREAD

**Issue by wswm2009** [tobefuturer/app2dylib#5]
你好，请问下出现如下错误
2016-11-30 14:13:44.676 FacetuneDemo[4112:33011] dlopen failed ，error  

而且dlerror  貌似没有出现具体错误信息，是不是你说的需要codesign？   我转完dylib直接拖进工程，就这样，

**Comment by wswm2009** [comment]
我这个app  是decrypted之后  再转成dylib的   没影响吧

**Comment by tobefuturer** [comment]
要和工程主app的签名证书一致的，肯定是要decrypted 才能转app的

**Comment by wswm2009** [comment]
谢谢你的回答，  我就是把dylib拖进工程  生成到真机上    调试出现dlopen Failed  没有error？

**Comment by tobefuturer** [comment]
http://blog.imjun.net/2016/10/08/%E9%BB%91%E7%A7%91%E6%8A%80%EF%BC%9A%E6%8A%8A%E7%AC%AC%E4%B8%89%E6%96%B9-iOS-%E5%BA%94%E7%94%A8%E8%BD%AC%E6%88%90%E5%8A%A8%E6%80%81%E5%BA%93/

你用这个网页里最后的那段代码试试看，
