### ISSUE TITLE
真机失败，模拟器可以

### ISSUE THREAD

**Issue by hellofrida** [tobefuturer/app2dylib#8]
尝试新建一个工程，让后app2dylib，模拟器可以，但真机不行，具体错误提示都没有

**Comment by tobefuturer** [comment]
那个二进制能发我看看吗

杨君

**Comment by hellofrida** [comment]
当然可以，非常，荣幸，感谢，那我把相关文件发给你的gmail。

自己的开发者创建的测试程序，不知要不要重新签名

**Comment by hellofrida** [comment]
我好像没签名，低级错误

**Comment by tobefuturer** [comment]
要签名，签名的示例脚本，在blog里面，http://blog.imjun.net/posts/convert-iOS-app-to-dynamic-library/ github 那个readme页面 我没太细写

**Comment by hellofrida** [comment]
之前失败是因为 电脑是x86_64 位的，手机需要amv64,签名后就可以，如果能通过审核上线就非常厉害了。

**Comment by tobefuturer** [comment]
上线审核倒是没啥问题，dylib可能要用framework包一下，他们审核也看不出这个

**Comment by hellofrida** [comment]
关于绕过检测代码的部分；
经过测试，在新生成的dylib中 使用yololib 加入一个dylib，然后使用CaptainHook hook需要的方法，一样可以达到绕过或者hook的目的。

如果能够删除一些不要的方法或者类就好了，因为只要关键算法逻辑部分的话，核心逻辑不会很多，不然这个dylib 和mach-o 一样大，但很大部分是没有实际作用的

**Comment by yucca1012** [comment]
@tobefuturer  我用了一个空的二进制，用app2dylib转成dylib,并且用framework包了一下，上传到iTunesConnect试了一下，报错：The app contains one or more corrupted binaries. Rebuild the app and resubmit.
苹果似乎目前认为这种macho转换成的动态库是有格式上的问题的
